### ISSUE TITLE
Page goes dark with some widgets, ie. add reaction

### ISSUE THREAD

**Issue by eras** [Bigsy/dark-slack-theme#11]
Seems like a Slack update broke it.

Easiest way to reproduce:
1) Find a message
2) Open the add reaction-popup for the message
3) Notice how the rest of the page goes dark (invisible text)

This does not occur with this add-on disabled.

Thanks for making Slack bearable ;-).

**Comment by greenembrace** [comment]
I'm also having this issue. It's been so great to darken the night. Hope this can be resolved.

**Comment by im-strongthany-zz** [comment]
Same issue. Using on Firefox Nightly with the new version of slack(23-7-2019). Formatting on page looks off, searching for emotes blacks out the whole screen. Please let me know if there is any data I can provide to hep with this issue. Thanks.

**Comment by Bigsy** [comment]
Thanks for raising I will look to fix this over the weekend.

**Comment by geojoek** [comment]
Also having this issue... page just goes black and white with all other colors, etc... missing, in addition to widgets, etc...

**Comment by im-strongthany-zz** [comment]
Hey @Bigsy, have you had a chance to dig into this issue yet? I don't mean to be a bother.

**Comment by Bigsy** [comment]
I will fix this issue but I'm on my summer holiday at the moment and
finding it difficult to find the time. I will be home on Monday and intend
to push a fix then.

**Comment by Bigsy** [comment]
Should be fixed in the version I just published (1.5.5). Give it 15mins from now and refresh extensions.

**Comment by im-strongthany-zz** [comment]
Seems to work, please close this. Thank you.
