### ISSUE TITLE
permission to read browser history 

### ISSUE THREAD

**Issue by jaredatron** [Bigsy/dark-slack-theme#12]
I've uninstalled this (as a chrome extension) because it is now asking me for permission to read my browser history. Why do you need that information to inject some CSS?

**Comment by Bigsy** [comment]
There is no CSS here, but yes you are correct I use additional permissions to debug and sometimes forget to removed again. A new version has been published you should be able to update in 20mins or so.

**Comment by jaredatron** [comment]
No css huh? Amazing. I'll try reinstalling it later. Thanks
