### ISSUE TITLE
Unreadable channel @

### ISSUE THREAD

**Issue by bunnybooboo** [Bigsy/dark-slack-theme#4]
I feel like the colours might need a little tweak. If someone `@everyone` or `@here` the text is unreadable.

![screenshot from 2017-09-26 10-11-37](https://user-images.githubusercontent.com/5793295/30853118-cf34467a-a2a5-11e7-9c52-00f5aca07c37.png)

**Comment by Bigsy** [comment]
Took awhile to get around to but I did quickly correct this
