### ISSUE TITLE
Right sidebar not affected by changes

### ISSUE THREAD

**Issue by bunnybooboo** [Bigsy/dark-slack-theme#5]
Selecting a thread conversation, a user profile, an app etc has the right sidebar in the default white instead of black background.

**Comment by Regnander** [comment]
Any updates on this?

**Comment by Bigsy** [comment]
I don't seem to have this problem, if I select a user profile it pops up on the right and is the correct (non white) colour, the text is barely readable so I can fix that, but I'm not seeing your issue. Have you tried reinstalling the extension?

**Comment by Regnander** [comment]
Heh, I just realized that I didn't properly read the original post and thought it was about the sidebar in the preferences, which happens to be unreadable at the moment:

![slack-preferences-dark-theme](https://user-images.githubusercontent.com/17113053/39021037-602c36da-442f-11e8-9430-ae036174184a.png)
