### ISSUE TITLE
@myusername not hilighted

### ISSUE THREAD

**Issue by bezda** [Bigsy/dark-slack-theme#6]
Appearing as all other @someoneelse, would be great to have slightly different text colour/background when displaying notification for myself

**Comment by Regnander** [comment]
The same goes with keywords.

**Comment by Regnander** [comment]
Issue #4 addresses this problem, and while it is much better than it was earlier, it still can be improved with a slightly darker text.

![slack-mention](https://user-images.githubusercontent.com/17113053/38782648-13185292-40f7-11e8-8e80-55064d6637a8.png)
