### ISSUE TITLE
Unreadable keywords

### ISSUE THREAD

**Issue by Regnander** [Bigsy/dark-slack-theme#7]
Keywords are unreadable, as shown in the screenshot below:

![slack-keyword](https://user-images.githubusercontent.com/17113053/38782764-6f5dc98c-40f8-11e8-8998-93984c7ceb50.png)

**Comment by Regnander** [comment]
It would be nice if you gave a reason for closing all existing issues. Are you planning to rewrite the add-on or did you solve all issues but never committed them to this repo?

**Comment by Bigsy** [comment]
It was completely rewritten some time ago.

**Comment by Regnander** [comment]
Awesome! I'd love to try it out when the update comes.

**Comment by Bigsy** [comment]
It was released on chrome store 5 months ago :)

**Comment by Regnander** [comment]
Oh, I'm using Firefox. :disappointed:

**Comment by Bigsy** [comment]
Firefox was updated at the same time.

**Comment by Regnander** [comment]
Wow, I feel so dumb right now for misreading the Firefox add-on history as "Mar 24" (as in March 24) instead of "May 24". :man_facepalming: 
I just downloaded the add-on and the flaws I had earlier are now ironed out. Thanks a million times!

Although, I have a suggestion for an improvement, but I'll create a new issue for that.
