### ISSUE TITLE
Broken again for chrome

### ISSUE THREAD

**Issue by thongraegu** [Bigsy/dark-slack-theme#8]
https://i.gyazo.com/ede9cb5eb2f0902b739b5562ba155bcc.png

since today everything in text area is white unless you hover mouse over it.

**Comment by pierreraby** [comment]
I confirm this issue

**Comment by MikeRatcliffe** [comment]
Same with Firefox

**Comment by benjamingr** [comment]
Confirm the issue

**Comment by petroslegato** [comment]
Confirm on Chrome 65.0.3325.181 (MacOS, 64-bit)

**Comment by Bigsy** [comment]
I was planning committing a redo of the entirety of the css mess that's there but probably don't have time to finish that today....guess I'll just patch this up later today as is when I get back from work.

**Comment by benjamingr** [comment]
Thanks! I'm really enjoying your work and just wanted to thank you personally for developing this.

**Comment by Bigsy** [comment]
The main issue is now fixed, there could be others but I dont have time to search atm. 

Will need to force an extension update in chrome as google as its slow at updating itself. Might need to give it a half hour as well to make sure its fully published.

Firefox also fixed.
